apiVersion: v1
kind: Service
metadata:
  name: rube
  namespace: rube
  labels:
    app: rube
spec:
  selector:
    app: rube
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rube
  namespace: rube
  labels:
    app: rube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rube
  template:
    metadata:
      labels:
        app: rube
    spec:
      containers:
      - name: rube
        image: us-west1-docker.pkg.dev/foyle-public/images/rube/rube-dcd0431509013ed6173fca865862582f@sha256:78accb3231e0dcfa14b196a31a880c45b937faf3992b27f80198573f4136e62a
        args:
        - --honeycomb-apikey=gcpsecretmanager:///projects/foyle-dev/secrets/honeycomb-api-key/versions/latest
        - --openai-apikey=gcpsecretmanager:///projects/foyle-dev/secrets/NEEDSTOBESET/versions/latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
      serviceAccountName: rube