apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rube
nameSuffix: -prod
labels:
  - pairs:      
      env: prod
    includeSelectors: true
patches:
- path: deployment-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
resources:
- ../base
- httproute.yaml