kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: rube
  namespace: rube
  labels:
    gateway: external-http
spec:
  parentRefs:
  - name: external-http
    namespace: gateway
  hostnames:
  - "dev.foyle.io"  
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /demo/dev
    filters:
      - type: URLRewrite
        urlRewrite:          
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /
    backendRefs:
    - name: rube
      port: 80

---

# Configure an HTTPHealthCheck so we use /healthz

apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: rube
  namespace: rube
spec:
  default:
    config:
      type: HTTP 
      httpHealthCheck:        
        requestPath: /healthz              
  targetRef:
    group: ""
    kind: Service
    name: rube
